//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogiLockLED.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCaps {
            get {
                return ((bool)(this["EnableCaps"]));
            }
            set {
                this["EnableCaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CapsOnColour {
            get {
                return ((global::System.Drawing.Color)(this["CapsOnColour"]));
            }
            set {
                this["CapsOnColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CapsOffColour {
            get {
                return ((global::System.Drawing.Color)(this["CapsOffColour"]));
            }
            set {
                this["CapsOffColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color NumOnColour {
            get {
                return ((global::System.Drawing.Color)(this["NumOnColour"]));
            }
            set {
                this["NumOnColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color NumOffColour {
            get {
                return ((global::System.Drawing.Color)(this["NumOffColour"]));
            }
            set {
                this["NumOffColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableNum {
            get {
                return ((bool)(this["EnableNum"]));
            }
            set {
                this["EnableNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableScroll {
            get {
                return ((bool)(this["EnableScroll"]));
            }
            set {
                this["EnableScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ScrollOnColour {
            get {
                return ((global::System.Drawing.Color)(this["ScrollOnColour"]));
            }
            set {
                this["ScrollOnColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ScrollOffColour {
            get {
                return ((global::System.Drawing.Color)(this["ScrollOffColour"]));
            }
            set {
                this["ScrollOffColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableKeyLockLEDs {
            get {
                return ((bool)(this["EnableKeyLockLEDs"]));
            }
            set {
                this["EnableKeyLockLEDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 48pt, style=Bold, Italic")]
        public global::System.Drawing.Font OsdFont {
            get {
                return ((global::System.Drawing.Font)(this["OsdFont"]));
            }
            set {
                this["OsdFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Centre")]
        public string OsdPosition {
            get {
                return ((string)(this["OsdPosition"]));
            }
            set {
                this["OsdPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int OsdPadding {
            get {
                return ((int)(this["OsdPadding"]));
            }
            set {
                this["OsdPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int OsdMargin {
            get {
                return ((int)(this["OsdMargin"]));
            }
            set {
                this["OsdMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OsdRoundedCorners {
            get {
                return ((bool)(this["OsdRoundedCorners"]));
            }
            set {
                this["OsdRoundedCorners"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OsdEnabled {
            get {
                return ((bool)(this["OsdEnabled"]));
            }
            set {
                this["OsdEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color OsdTextColour {
            get {
                return ((global::System.Drawing.Color)(this["OsdTextColour"]));
            }
            set {
                this["OsdTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 3, 3")]
        public global::System.Drawing.Color OsdBackColour {
            get {
                return ((global::System.Drawing.Color)(this["OsdBackColour"]));
            }
            set {
                this["OsdBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int OsdOpacity {
            get {
                return ((int)(this["OsdOpacity"]));
            }
            set {
                this["OsdOpacity"] = value;
            }
        }
    }
}
